name: Build on Push

on: [push]

jobs:
  testGoDepVendor:
    name: Test Go Dep Vendor
    runs-on: ubuntu-latest
    steps:
    -  run: go vet
  checkFormatting:
    name: Check Formatting
    runs-on: ubuntu-latest
    steps: 
    - run: go fmt
  buildApp:
    name: Build the app
    runs-on: ubuntu-latest
    steps: 
    - name: go build
      run: go build -o portal ./cmd/vpn-portal/...
  buildContainer:
    name: Build the app
    using: quay.io/podman/stable
    runs-on: ubuntu-latest
    steps: 
    - name: docker build
      run: docker build -f build/package/Dockerfile .
